### ISSUE TITLE
Error in Xray logs

### ISSUE THREAD

**Issue by andreyzhm** [aws-samples/aws-xray-fargate#1]
Hi guys, I have followed your guide and spinned the services but when looking at xray logs I can see:

16:30:48
2018-05-22T15:30:48Z [Info] Initializing AWS X-Ray daemon 2.1.2

16:30:48
2018-05-22T15:30:48Z [Info] Using buffer memory limit of 39 MB

16:30:48
2018-05-22T15:30:48Z [Info] 624 segment buffers allocated

16:30:48
2018-05-22T15:30:48Z [Info] Using region: us-east-1

16:30:49
2018-05-22T15:30:49Z [Error] Get instance id metadata failed: RequestError: send request failed

16:30:49
caused by: Get http://169.254.169.254/latest/meta-data/instance-id: dial tcp 169.254.169.254:80: connect: invalid argument
caused by: Get http://169.254.169.254/latest/meta-data/instance-id: dial tcp 169.254.169.254:80: connect: invalid argument

**Comment by jicowan** [comment]
Could be an issue with the security groups associated with the task.  Can you verify that 80 and/or all traffic outbound is allowed?

**Comment by andreyzhm** [comment]
http://169.254.169.254/ is the instance metadata for ec2 right. When running with fargate we don't have this endpoint. 
Also the ports are open

**Comment by jicowan** [comment]
That's right.  I forgot to remove EC2 from the config parameters for X-Ray.  Thanks for finding the bug.  I updated the js files for service a and b.

**Comment by Jose-Carbonell** [comment]
@jicowan how I can remove EC2 from the config parameters for X-Ray?

**Comment by jicowan** [comment]
It's already been done

**Comment by Yusadolat** [comment]
I still faced this bug. Any workaround, please?
