### ISSUE TITLE
Issue on fargate when using ECS plugin

### ISSUE THREAD

**Issue by andreyzhm** [aws-samples/aws-xray-fargate#2]
I think that ECS plugin is not working for fargate at least:

2018-05-23 09:13:18.951 ERROR 7 --- [ main] com.amazonaws.xray.plugins.ECSPlugin : Could not get docker container ID from hostname.

This is due to the fact that fargate container hostname is not really something that can be resolved to IP, when I had similar problem I had to fetch the IP from the task metadata endpoint

**Comment by jicowan** [comment]
Ok, although the task meta data endpoint is accessible from within a Fargate task.  That's how solutions like Datadog can get Docker stats for Fargate containers.  You can remove from the config too.  Are the traces working, i.e. can you see segments in X-Ray?

**Comment by andreyzhm** [comment]
Yea. Thanks
I can see traces
