### ISSUE TITLE
cluster_name to be specified in ecs-cli compose service up command

### ISSUE THREAD

**Issue by khanna-vijay** [aws-samples/aws-xray-fargate#4]
the current command does not mention the cluster name, and hence the service is not getting created. Need to add --cluster option to command as below. 

ecs-cli compose service up --deployment-max-percent 100 --deployment-min-healthy-percent 0 --target-group-arn $TARGET_GROUP_ARN --launch-type FARGATE --container-name service-b --container-port 8080 --cluster <cluster_name>

**Comment by jicowan** [comment]
fixed.
